In [1]:
import pandas as pd
import os
import numpy as np
import seaborn as sns
import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
import scipy.stats as stats
from matplotlib.patches import Rectangle
import matplotlib.pyplot as plt

Dir_github = '/work/desai-lab/xuanyang/Project/Semantic/dissemination/github/DiscoFMRI'
# Dir_github = r'Z:\study\phd\project\Semantics\FactorAnalysis\github'

Dir_output = os.path.join(Dir_github,'data','FactorAnalysis')

/home/xy6/.local/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [2]:

import numpy as np
from scipy.stats import t, norm
from math import atanh, pow
from numpy import tanh

def rz_ci(r, n, conf_level = 0.95):
    zr_se = pow(1/(n - 3), .5)
    moe = norm.ppf(1 - (1 - conf_level)/float(2)) * zr_se
    zu = atanh(r) + moe
    zl = atanh(r) - moe
    return tanh((zl, zu))

def rho_rxy_rxz(rxy, rxz, ryz):
    num = (ryz-1/2.*rxy*rxz)*(1-pow(rxy,2)-pow(rxz,2)-pow(ryz,2))+pow(ryz,3)
    den = (1 - pow(rxy,2)) * (1 - pow(rxz,2))
    return num/float(den)

def dependent_corr(xy, xz, yz, n, twotailed=True, conf_level=0.95, method='steiger'):
    """
    Calculates the statistic significance between two dependent correlation coefficients
    @param xy: correlation coefficient between x and y
    @param xz: correlation coefficient between x and z
    @param yz: correlation coefficient between y and z
    @param n: number of elements in x, y and z
    @param twotailed: whether to calculate a one or two tailed test, only works for 'steiger' method
    @param conf_level: confidence level, only works for 'zou' method
    @param method: defines the method uses, 'steiger' or 'zou'
    @return: t and p-val
    """
    if method == 'steiger':
        d = xy - xz
        determin = 1 - xy * xy - xz * xz - yz * yz + 2 * xy * xz * yz
        av = (xy + xz)/2
        cube = (1 - yz) * (1 - yz) * (1 - yz)

        t2 = d * np.sqrt((n - 1) * (1 + yz)/(((2 * (n - 1)/(n - 3)) * determin + av * av * cube)))
        p = 1 - t.cdf(abs(t2), n - 3)

        if twotailed:
            p *= 2

        return t2, p
    elif method == 'zou':
        L1 = rz_ci(xy, n, conf_level=conf_level)[0]
        U1 = rz_ci(xy, n, conf_level=conf_level)[1]
        L2 = rz_ci(xz, n, conf_level=conf_level)[0]
        U2 = rz_ci(xz, n, conf_level=conf_level)[1]
        rho_r12_r13 = rho_rxy_rxz(xy, xz, yz)
        lower = xy - xz - pow((pow((xy - L1), 2) + pow((U2 - xz), 2) - 2 * rho_r12_r13 * (xy - L1) * (U2 - xz)), 0.5)
        upper = xy - xz + pow((pow((U1 - xy), 2) + pow((xz - L2), 2) - 2 * rho_r12_r13 * (U1 - xy) * (xz - L2)), 0.5)
        return lower, upper
    else:
        raise Exception('Wrong method!')

In [3]:
NFA = 8
df_FA_behav = pd.read_csv(os.path.join(Dir_output,f'df_FA8_behav_merged.csv'))
df_loadings = pd.read_csv(os.path.join(Dir_output,f'FA_n{NFA}_loadings.csv'))
List_106vars = list(df_loadings['index'])
List_FAs = [f'FA{x}' for x in range(1,NFA+1)]

List_Y5 = [x for x in df_FA_behav.columns if ('_ACC_' in x) or ('_RT' in x) or x == 'Recog_Memory']
List_Y3 = [x for x in List_Y5 if 'SemanticD' not in x and 'Recog_Memory' not in x ]
List_Y4 = [x for x in List_Y5 if 'Recog_Memory' not in x]


dict_behav = {'RT_LD_V':['LexicalD_RT_V_ELP_z','LexicalD_RT_V_ECP_z','LexicalD_RT_V_BLP_z'],
                 'RT_LD_A':['LexicalD_RT_A_MALD_z','LexicalD_RT_A_AELP_z'],
                 'ACC_LD_V':['LexicalD_ACC_V_ELP','LexicalD_ACC_V_ECP','LexicalD_ACC_V_BLP'],
                 'ACC_LD_A':['LexicalD_ACC_A_MALD','LexicalD_ACC_A_AELP'],
                 'ACC_Naming':['Naming_ACC_ELP'],
                 'RT_Naming':['Naming_RT_ELP_z'],
                 'ACC_SD':['SemanticD_ACC_Calgary'],
                 'RT_SD':['SemanticD_RT_Calgary_z'],
                 'ACC_Recog':['Recog_Memory']
             }
dict_behav_combine = {'ACC(3tasks)':['ACC_LD_V','ACC_LD_A','ACC_Naming'],
                      'ACC(4tasks)':['ACC_LD_V','ACC_LD_A','ACC_Naming','ACC_SD'],
                      'ACC(5tasks)':['ACC_LD_V','ACC_LD_A','ACC_Naming','ACC_SD','ACC_Recog'],
                      'RT(3tasks)':['RT_LD_V','RT_LD_A','RT_Naming'],
                      'RT(4tasks)':['RT_LD_V','RT_LD_A','RT_Naming','RT_SD']}
# dict_behav_combine = {'ACC(3tasks)':['ACC_LD_V','ACC_LD_A','ACC_Naming'],
#                       'ACC(4tasks)':['ACC_LD_V','ACC_LD_A','ACC_Naming','ACC_SD'],
#                       'RT(3tasks)':['RT_LD_V','RT_LD_A','RT_Naming'],
#                       'RT(4tasks)':['RT_LD_V','RT_LD_A','RT_Naming','RT_SD']}


options = {'List_FAs':List_FAs,'List_Y4':List_Y4,'List_Y5':List_Y5,
          'dict_behav':dict_behav,'dict_behav_combine':dict_behav_combine,
          'df_FA_behav':df_FA_behav,
          'df_loadings':df_loadings
          }

In [4]:
def compare_r(options,bestN):
    List_Y = options['List_Y5']
    df_FA_behav = options['df_FA_behav']
    df_loadings = options['df_loadings']
    
    
    
    dfs_table = []
    for var in List_Y5:

        List_Y = [var]

        df_bestpred = df_FA_behav[List_106vars+List_FAs+List_Y].dropna()
        n = df_bestpred.shape[0]

        df_corr = df_bestpred.corr(method='spearman')

        df_table = []

        for iFA in range(1,9):
            List_var_tmp = list(df_loadings.loc[~df_loadings[f'Factor {iFA}'].isna(),'index'].values)
            df_r = df_corr.loc[List_var_tmp,List_Y].abs()
            df_rank = df_r.rank(ascending=False)

            best = df_rank.loc[df_rank[var]==bestN].index[0]
            best_r = df_r.loc[best,var]

            df_r = df_corr.loc[[f"FA{iFA}"]+List_var_tmp,List_Y].abs()
            df_rank = df_r.rank(ascending=False)

            FA_rank = df_rank.loc[f"FA{iFA}",var]
            FA_r = df_r.loc[f"FA{iFA}",var]
            df_table.append(pd.DataFrame({'variable':var,'best':best,'best r':best_r,'FA':f"FA{iFA}",'FA_rank':FA_rank,'FA_r':FA_r},index=[0]))

        df_table = pd.concat(df_table,ignore_index=True)

        for i, row in df_table.iterrows():

            x = row['variable']
            y = row['best']
            z = row['FA']
            if y!=z:

                corr_matrix = df_corr.loc[[x,y,z],[x,y,z]].abs()
                r_xy = corr_matrix.loc[x, y]  
                r_xz = corr_matrix.loc[x, z]  
                r_yz = corr_matrix.loc[y, z]  
        #             n = df_table.shape[0]  

                t2,p = dependent_corr(r_xy, r_xz, r_yz, n,twotailed=True,conf_level=0.95, method='steiger')
                df_table.loc[i,'t_steiger'] = t2
                df_table.loc[i,'p_steiger'] = p

        df_table['N'] = n
        dfs_table.append(df_table)
    dfs_table = pd.concat(dfs_table,ignore_index=True)
    dfs_table['p_steiger_FDR'] = stats.false_discovery_control(dfs_table['p_steiger'])
    return(dfs_table)

In [5]:
Nbest = 1

dfs_table = compare_r(options,Nbest)

# The factor scores outperform single variables
df = dfs_table.loc[dfs_table['t_steiger']<0].loc[dfs_table['p_steiger_FDR']<.05]
for i,row in df.iterrows():
    print(f"{row['FA']} is the {Nbest} best in predicting {row['variable']}")


# The single variables outperform factor scores 
dfs_table.loc[dfs_table['t_steiger']>0].loc[dfs_table['p_steiger_FDR']<.05]

FA7 is the 1 best in predicting LexicalD_RT_V_BLP_z
FA7 is the 1 best in predicting LexicalD_ACC_V_ELP
FA7 is the 1 best in predicting LexicalD_ACC_V_BLP

,variable,best,best r,FA,FA_rank,FA_r,t_steiger,p_steiger,N,p_steiger_FDR
1,LexicalD_RT_V_ELP_z,NLett,0.519464,FA2,6.0,0.435430,22.467356,0.000000e+00,11617,0.000000e+00
2,LexicalD_RT_V_ELP_z,Consistency_Token_FB_ON,0.040339,FA3,8.0,0.002943,6.354156,2.174145e-10,11617,5.671683e-10
3,LexicalD_RT_V_ELP_z,Consistency_Token_FF_R,0.197958,FA4,6.0,0.045782,16.582020,0.000000e+00,11617,0.000000e+00
5,LexicalD_RT_V_ELP_z,AoA_LWV,0.470621,FA6,3.0,0.236314,29.280698,0.000000e+00,11617,0.000000e+00
7,LexicalD_RT_V_ELP_z,Assoc_Freq_Token123,0.433700,FA8,5.0,0.286981,17.360112,0.000000e+00,11617,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...
111,Naming_ACC_ELP,Assoc_Freq_Type123,0.160876,FA8,5.0,0.104291,6.113763,1.004328e-09,11617,2.459579e-09
112,SemanticD_ACC_Calgary,Nsenses_WordNet,0.150814,FA1,15.0,0.028077,6.281706,3.956857e-10,2427,1.010261e-09
115,SemanticD_ACC_Calgary,Consistency_Type_FF_R,0.106698,FA4,7.0,0.052408,2.731856,6.343516e-03,2427,1.014963e-02
116,SemanticD_ACC_Calgary,TrigramF_Avg_C_Log,0.162491,FA5,6.0,0.064499,4.713177,2.576919e-06,2427,4.987585e-06
119,SemanticD_ACC_Calgary,Assoc_Freq_Token123,0.159551,FA8,4.0,0.121998,2.130903,3.319751e-02,2427,4.799641e-02

In [48]:
df = dfs_table.loc[~((dfs_table['t_steiger']>0) & (dfs_table['p_steiger_FDR']<.05))].copy()
df.loc[df['variable'].str.contains('_RT_'),'type'] = 'RT'
df.loc[~df['variable'].str.contains('_RT_'),'type'] = 'ACC'
df.loc[df['variable'].str.contains('LexicalD'),'task'] = 'LD'
df.loc[df['variable'].str.contains('SemanticD'),'task'] = 'SD'
df.loc[df['variable'].str.contains('Naming'),'task'] = 'Naming'
df.groupby(['FA','type','task']).count()

                 variable  best  best r  FA_rank  FA_r  t_steiger  p_steiger  \
FA  type task
FA1 ACC  Naming         1     1       1        1     1          1          1
    RT   LD             1     1       1        1     1          1          1
FA2 ACC  LD             2     2       2        2     2          2          2
         SD             1     1       1        1     1          1          1
FA3 ACC  LD             2     2       2        2     2          2          2
         SD             1     1       1        1     1          1          1
    RT   LD             4     4       4        4     4          4          4
         SD             1     1       1        1     1          1          1
FA4 ACC  LD             2     2       2        2     2          2          2
    RT   LD             2     2       2        2     2          2          2
FA5 ACC  Naming         1     1       1        1     1          1          1
    RT   LD             2     2       2        2     2          2          2
         Naming         1     1       1        1     1          1          1
         SD             1     1       1        1     1          1          1
FA6 ACC  SD             1     1       1        1     1          1          1
    RT   SD             1     1       1        1     1          1          1
FA7 ACC  LD             5     5       5        5     5          5          5
         Naming         1     1       1        1     1          1          1
         SD             1     1       1        1     1          1          1
    RT   LD             3     3       3        3     3          3          3
         Naming         1     1       1        1     1          1          1
FA8 ACC  LD             1     1       1        1     1          1          1
    RT   LD             1     1       1        1     1          1          1

                 N  p_steiger_FDR
FA  type task
FA1 ACC  Naming  1              1
    RT   LD      1              1
FA2 ACC  LD      2              2
         SD      1              1
FA3 ACC  LD      2              2
         SD      1              1
    RT   LD      4              4
         SD      1              1
FA4 ACC  LD      2              2
    RT   LD      2              2
FA5 ACC  Naming  1              1
    RT   LD      2              2
         Naming  1              1
         SD      1              1
FA6 ACC  SD      1              1
    RT   SD      1              1
FA7 ACC  LD      5              5
         Naming  1              1
         SD      1              1
    RT   LD      3              3
         Naming  1              1
FA8 ACC  LD      1              1
    RT   LD      1              1

### The second best

In [9]:
Nbest = 2

dfs_table = compare_r(options,Nbest)

# The factor scores outperform single variables
df = dfs_table.loc[dfs_table['t_steiger']<0].loc[dfs_table['p_steiger_FDR']<.05]
for i,row in df.iterrows():
    print(f"{row['FA']} is the {Nbest} best in predicting {row['variable']}")


# The single variables outperform factor scores 
dfs_table.loc[dfs_table['t_steiger']>0].loc[dfs_table['p_steiger_FDR']<.05]

FA1 is the 2 best in predicting LexicalD_RT_V_ELP_z
FA7 is the 2 best in predicting LexicalD_RT_V_ELP_z
FA5 is the 2 best in predicting LexicalD_RT_V_ECP_z
FA7 is the 2 best in predicting LexicalD_RT_V_BLP_z
FA3 is the 2 best in predicting Recog_Memory
FA6 is the 2 best in predicting Recog_Memory
FA7 is the 2 best in predicting LexicalD_ACC_V_ELP
FA7 is the 2 best in predicting LexicalD_ACC_V_BLP
FA2 is the 2 best in predicting LexicalD_ACC_A_AELP
FA1 is the 2 best in predicting Naming_ACC_ELP
FA5 is the 2 best in predicting Naming_ACC_ELP

,variable,best,best r,FA,FA_rank,FA_r,t_steiger,p_steiger,N,p_steiger_FDR
1,LexicalD_RT_V_ELP_z,NPhon,0.481339,FA2,6.0,0.435430,12.597197,0.000000e+00,11617,0.000000e+00
2,LexicalD_RT_V_ELP_z,Consistency_Type_FB_ON,0.037025,FA3,8.0,0.002943,5.819115,6.072278e-09,11617,1.777252e-08
3,LexicalD_RT_V_ELP_z,Consistency_Type_FF_R,0.193558,FA4,6.0,0.045782,16.090698,0.000000e+00,11617,0.000000e+00
5,LexicalD_RT_V_ELP_z,AoA_Kuper,0.459814,FA6,3.0,0.236314,27.444722,0.000000e+00,11617,0.000000e+00
7,LexicalD_RT_V_ELP_z,Assoc_Freq_Type123,0.429567,FA8,5.0,0.286981,16.807937,0.000000e+00,11617,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...
109,Naming_ACC_ELP,AoA_Kuper,0.208888,FA6,4.0,0.103916,11.762263,0.000000e+00,11617,0.000000e+00
111,Naming_ACC_ELP,Assoc_Freq_Token123,0.160738,FA8,5.0,0.104291,6.110511,1.024941e-09,11617,3.153666e-09
112,SemanticD_ACC_Calgary,AoA_Kuper,0.112081,FA1,15.0,0.028077,4.464284,8.401478e-06,2427,1.976818e-05
115,SemanticD_ACC_Calgary,Consistency_Token_FF_R,0.104060,FA4,7.0,0.052408,2.599825,9.383751e-03,2427,1.521689e-02
116,SemanticD_ACC_Calgary,TrigramF_Avg_U_Log,0.122808,FA5,6.0,0.064499,2.866251,4.189473e-03,2427,7.181954e-03

In [10]:
Nbest = 3

dfs_table = compare_r(options,Nbest)

# The factor scores outperform single variables
df = dfs_table.loc[dfs_table['t_steiger']<0].loc[dfs_table['p_steiger_FDR']<.05]
for i,row in df.iterrows():
    print(f"{row['FA']} is the {Nbest} best in predicting {row['variable']}")


# The single variables outperform factor scores 
dfs_table.loc[dfs_table['t_steiger']>0].loc[dfs_table['p_steiger_FDR']<.05]

FA1 is the 3 best in predicting LexicalD_RT_V_ELP_z
FA6 is the 3 best in predicting LexicalD_RT_V_ELP_z
FA7 is the 3 best in predicting LexicalD_RT_V_ELP_z
FA3 is the 3 best in predicting LexicalD_RT_V_ECP_z
FA5 is the 3 best in predicting LexicalD_RT_V_ECP_z
FA1 is the 3 best in predicting LexicalD_RT_V_BLP_z
FA3 is the 3 best in predicting LexicalD_RT_V_BLP_z
FA7 is the 3 best in predicting LexicalD_RT_V_BLP_z
FA3 is the 3 best in predicting LexicalD_RT_A_AELP_z
FA5 is the 3 best in predicting Naming_RT_ELP_z
FA6 is the 3 best in predicting Naming_RT_ELP_z
FA3 is the 3 best in predicting SemanticD_RT_Calgary_z
FA6 is the 3 best in predicting SemanticD_RT_Calgary_z
FA3 is the 3 best in predicting Recog_Memory
FA6 is the 3 best in predicting Recog_Memory
FA1 is the 3 best in predicting LexicalD_ACC_V_ELP
FA7 is the 3 best in predicting LexicalD_ACC_V_ELP
FA1 is the 3 best in predicting LexicalD_ACC_V_ECP
FA2 is the 3 best in predicting LexicalD_ACC_V_ECP
FA1 is the 3 best in predicting LexicalD_ACC_V_BLP
FA2 is the 3 best in predicting LexicalD_ACC_V_BLP
FA3 is the 3 best in predicting LexicalD_ACC_V_BLP
FA7 is the 3 best in predicting LexicalD_ACC_V_BLP
FA2 is the 3 best in predicting LexicalD_ACC_A_AELP
FA6 is the 3 best in predicting LexicalD_ACC_A_AELP
FA1 is the 3 best in predicting Naming_ACC_ELP
FA5 is the 3 best in predicting Naming_ACC_ELP
FA3 is the 3 best in predicting SemanticD_ACC_Calgary

,variable,best,best r,FA,FA_rank,FA_r,t_steiger,p_steiger,N,p_steiger_FDR
1,LexicalD_RT_V_ELP_z,OLD20,0.469997,FA2,6.0,0.435430,11.003079,0.000000e+00,11617,0.000000e+00
2,LexicalD_RT_V_ELP_z,Consistency_Type_FB,0.029239,FA3,8.0,0.002943,10.546635,0.000000e+00,11617,0.000000e+00
3,LexicalD_RT_V_ELP_z,Consistency_Token_FF,0.113207,FA4,6.0,0.045782,26.013609,0.000000e+00,11617,0.000000e+00
7,LexicalD_RT_V_ELP_z,Assoc_Freq_Token,0.392000,FA8,5.0,0.286981,12.800105,0.000000e+00,11617,0.000000e+00
9,LexicalD_RT_V_ECP_z,NPhon,0.363979,FA2,11.0,0.200888,31.713623,0.000000e+00,7449,0.000000e+00
11,LexicalD_RT_V_ECP_z,Consistency_Token_FF_N,0.035225,FA4,7.0,0.011257,3.643305,2.709908e-04,7449,5.511677e-04
13,LexicalD_RT_V_ECP_z,Mink_Perceptual_Lanc,0.275475,FA6,4.0,0.212056,6.779423,1.298828e-11,7449,7.084515e-11
15,LexicalD_RT_V_ECP_z,Assoc_Freq_Type,0.531204,FA8,5.0,0.427146,12.638327,0.000000e+00,7449,0.000000e+00
17,LexicalD_RT_V_BLP_z,NPhon,0.265277,FA2,12.0,0.091665,26.728923,0.000000e+00,9608,0.000000e+00
19,LexicalD_RT_V_BLP_z,Consistency_Type_FF,0.032713,FA4,5.0,0.025148,2.914796,3.567430e-03,9608,6.204226e-03
21,LexicalD_RT_V_BLP_z,Mink_Perceptual_Lanc,0.182350,FA6,4.0,0.118893,7.503499,6.772360e-14,9608,4.063416e-13
23,LexicalD_RT_V_BLP_z,Assoc_Freq_Type,0.352747,FA8,5.0,0.299545,6.280216,3.527496e-10,9608,1.628075e-09
24,LexicalD_RT_A_MALD_z,Cumfreq_TASA,0.179316,FA1,9.0,0.146549,4.405241,1.066922e-05,10720,2.845126e-05
25,LexicalD_RT_A_MALD_z,NMorph,0.151459,FA2,8.0,0.130766,2.235315,2.541718e-02,10720,3.910335e-02
29,LexicalD_RT_A_MALD_z,Mink_Perceptual_Lanc,0.135477,FA6,4.0,0.102790,4.079346,4.548945e-05,10720,1.070340e-04
30,LexicalD_RT_A_MALD_z,Sem_N_D_Taxonomic_N10,0.033901,FA7,5.0,0.012966,5.283690,1.290919e-07,10720,4.556183e-07
33,LexicalD_RT_A_AELP_z,NMorph,0.233267,FA2,8.0,0.178301,4.234065,2.340920e-05,4495,5.852301e-05
36,LexicalD_RT_A_AELP_z,TriphonP_Un,0.094356,FA5,8.0,0.067918,2.595644,9.472109e-03,4495,1.557059e-02
38,LexicalD_RT_A_AELP_z,Sem_N_D_Taxonomic_N10,0.131456,FA7,5.0,0.103655,5.063699,4.276628e-07,4495,1.387014e-06
39,LexicalD_RT_A_AELP_z,Assoc_Freq_Type,0.413721,FA8,5.0,0.315601,9.558574,0.000000e+00,4495,0.000000e+00
40,Naming_RT_ELP_z,Freq_Twitter_LemmaSum,0.396670,FA1,7.0,0.389987,2.196728,2.805960e-02,11617,4.262217e-02
41,Naming_RT_ELP_z,OLD20,0.482201,FA2,5.0,0.469113,4.207159,2.605444e-05,11617,6.253065e-05
43,Naming_RT_ELP_z,Consistency_Token_FF,0.175876,FA4,5.0,0.101177,29.220330,0.000000e+00,11617,0.000000e+00
47,Naming_RT_ELP_z,Assoc_Freq_Token,0.308999,FA8,5.0,0.216673,10.876908,0.000000e+00,11617,0.000000e+00
48,SemanticD_RT_Calgary_z,Cumfreq_TASA,0.233866,FA1,14.0,0.103629,8.886459,0.000000e+00,2426,0.000000e+00
49,SemanticD_RT_Calgary_z,NPhon,0.152815,FA2,13.0,0.021976,13.081045,0.000000e+00,2426,0.000000e+00
54,SemanticD_RT_Calgary_z,Sem_N_D_Taxonomic_N10,0.093609,FA7,5.0,0.069966,2.929379,3.428120e-03,2426,6.049624e-03
55,SemanticD_RT_Calgary_z,Assoc_Freq_Type123,0.298779,FA8,5.0,0.236095,3.703398,2.174833e-04,2426,4.499654e-04
56,Recog_Memory,CD_SUBTLEXUK_LemmaSum,0.355148,FA1,6.0,0.336525,3.781640,1.589196e-04,2924,3.467337e-04
57,Recog_Memory,OUP,0.099553,FA2,9.0,0.024756,6.769181,1.559197e-11,2924,8.134942e-11
60,Recog_Memory,TrigramF_Avg_U_Log,0.168300,FA5,6.0,0.073739,4.916058,9.318258e-07,2924,2.867156e-06
63,Recog_Memory,Assoc_Freq_Type,0.105872,FA8,8.0,0.041050,5.160955,2.621482e-07,2924,8.987939e-07
68,LexicalD_ACC_V_ELP,TrigramF_Avg_C_Log,0.030354,FA5,12.0,0.000763,2.940060,3.287950e-03,11626,5.888865e-03
69,LexicalD_ACC_V_ELP,Mink_Perceptual_Lanc,0.106699,FA6,7.0,0.053926,6.806042,1.052536e-11,11626,6.014490e-11
71,LexicalD_ACC_V_ELP,Assoc_Freq_Type,0.194111,FA8,5.0,0.167649,3.038704,2.381258e-03,11626,4.396168e-03
77,LexicalD_ACC_V_ECP,Mink_Perceptual_Lanc,0.177243,FA6,5.0,0.101094,7.950682,1.998401e-15,7449,1.410636e-14
79,LexicalD_ACC_V_ECP,Assoc_Freq_Type,0.309684,FA8,5.0,0.269875,4.310570,1.649313e-05,7449,4.302556e-05
83,LexicalD_ACC_V_BLP,Consistency_Type_FF,0.026691,FA4,7.0,0.006981,7.611308,2.975398e-14,9608,1.879199e-13
84,LexicalD_ACC_V_BLP,BigramF_Avg_U_Log,0.053199,FA5,12.0,0.005905,4.458540,8.345661e-06,9608,2.276089e-05
85,LexicalD_ACC_V_BLP,Mink_Perceptual_Lanc,0.129573,FA6,5.0,0.077087,6.155730,7.772198e-10,9608,3.330942e-09
87,LexicalD_ACC_V_BLP,Mink_Action_Lanc,0.183932,FA8,4.0,0.162707,2.406246,1.613616e-02,9608,2.547815e-02
90,LexicalD_ACC_A_MALD,Consistency_Token_FB,0.014749,FA3,7.0,0.002930,4.539850,5.690705e-06,10732,1.625916e-05
91,LexicalD_ACC_A_MALD,Consistency_Type_FF,0.022458,FA4,6.0,0.003907,6.604584,4.174949e-11,10732,2.087475e-10
96,LexicalD_ACC_A_AELP,Sem_Diversity,0.174878,FA1,8.0,0.125037,3.323484,8.961239e-04,4495,1.706903e-03
99,LexicalD_ACC_A_AELP,Consistency_Type_FF,0.099588,FA4,9.0,0.004959,22.076764,0.000000e+00,4495,0.000000e+00
100,LexicalD_ACC_A_AELP,BiphonP_St,0.248412,FA5,5.0,0.194473,5.872797,4.594093e-09,4495,1.901004e-08
105,Naming_ACC_ELP,NPhon,0.123107,FA2,9.0,0.097576,6.192662,6.115446e-10,11617,2.717976e-09
107,Naming_ACC_ELP,Consistency_Type_FF_R,0.115248,FA4,5.0,0.095069,2.169098,3.009544e-02,11617,4.514316e-02
111,Naming_ACC_ELP,Assoc_Freq_Type,0.130973,FA8,5.0,0.104291,3.024969,2.492026e-03,11617,4.530956e-03
112,SemanticD_ACC_Calgary,AoA_LWV,0.098000,FA1,15.0,0.028077,3.731268,1.948951e-04,2427,4.176323e-04
115,SemanticD_ACC_Calgary,Consistency_Type_FF,0.077616,FA4,7.0,0.052408,4.231740,2.405157e-05,2427,5.890180e-05
116,SemanticD_ACC_Calgary,UniphonP_St_C,0.091933,FA5,6.0,0.064499,2.258825,2.398279e-02,2427,3.737578e-02