In [1]:
import os
import pandas as pd
Dir_github = '/work/desai-lab/xuanyang/Project/Semantic/analysis/FactorAnalysis/github'
project = 'FactorAnalysis_fMRI'

In [2]:
mastersheetFile = '/work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/master/codes/master_subject_10stories_highacc.csv'
df_master = pd.read_csv(mastersheetFile)
df_master

,subID,task,age,sex,condition,comprehension,transcript,label,confounding,smooth_clean,nosmooth_clean,smooth_clean_rs,nosmooth_clean_rs,event
0,sub-023,prettymouth,28,F,affair,0.889,prettymouth,prettymouth,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...
1,sub-023,milkyway,28,F,vodka,1.000,milkywayvodka,milkywayvodka,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...
2,sub-030,prettymouth,21,F,paranoia,0.963,prettymouth,prettymouth,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...
3,sub-030,milkyway,21,F,vodka,0.893,milkywayvodka,milkywayvodka,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...
4,sub-032,prettymouth,22,M,affair,0.963,prettymouth,prettymouth,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
208,sub-314,piemanpni,25,F,NaN,0.767,piemanpni,piemanpni,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...
209,sub-314,bronx,25,F,NaN,0.780,bronx,bronx,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...
210,sub-314,forgot,25,F,NaN,0.780,forgot,forgot,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...
211,sub-314,black,25,F,NaN,0.920,black,black,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...
212,sub-315,black,35,M,NaN,0.600,black,black,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...

In [3]:
mastersheetFile = '/work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/master/codes/master_event_10stories_highacc.csv'
df_event = pd.read_csv(mastersheetFile)
df_event

,duration,onset,task,story,Nsubj,comprehension,duration_min
0,2225,14,21styear,21styear,10.0,1.0,55.625
1,533,8,black,black,47.0,1.0,13.325
2,357,8,bronx,bronx,47.0,1.0,8.925
3,558,8,forgot,forgot,47.0,1.0,13.950
4,269,14,milkyway,milkyway,34.0,1.0,6.725
5,267,8,piemanpni,piemanpni,47.0,1.0,6.675
6,451,14,prettymouth,prettymouth,35.0,1.0,11.275
7,272,33,shapessocial,shapessocial,58.0,1.0,6.800
8,602,20,slumlordreach,slumlord,16.0,1.0,15.050
9,550,646,slumlordreach,reach,16.0,1.0,13.750

In [5]:
import pandas as pd
import os
# df_timestamps = pd.read_csv('/work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/master/codes/Timestamps_10stories.csv')
df_timestamps = pd.read_csv('/work/desai-lab/xuanyang/Project/Semantic/analysis/FactorAnalysis/github/FactorAnalysis_fMRI/scripts/fMRI/timings/df_timings_15transcripts.csv')
df_timestamps['word_lower'] = df_timestamps['word'].str.lower()
df_timestamps['idx'] = range(len(df_timestamps))
df_timestamps['functional'] = 1
List_content = ['JJ','JJR','JJS',
                'NN','NNS','NNP','NNPS',
                'POS','PRP','PRP$',
                'RB','RBR','RBS',
                'VB','VBG','VBN','VBD','VBP','VBZ']
df_timestamps.loc[df_timestamps.PoS.isin(List_content),'functional'] =0 
df_timestamps

,Word,word_gentle,onset,offset,PoS,transcript,lemma,word,blankTR,onset_addblankTR,offset_addblankTR,word_lower,idx,functional
0,Tonight,tonight,0.12,0.48,NN,tunnel,tonight,tonight,2,3.12,3.48,tonight,0,0
1,a,a,0.69,0.80,DT,tunnel,a,a,2,3.69,3.80,a,1,1
2,story,story,0.80,1.21,NN,tunnel,story,story,2,3.80,4.21,story,2,0
3,by,by,1.21,1.46,IN,tunnel,by,by,2,4.21,4.46,by,3,1
4,Frederik,NaN,NaN,NaN,JJ,tunnel,frederik,frederik,2,NaN,NaN,frederik,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33319,tell,tell,407.41,407.61,VB,piemanpni,tell,tell,8,419.41,419.61,tell,33319,0
33320,me,me,407.61,407.77,PRP,piemanpni,me,me,8,419.61,419.77,me,33320,0
33321,all,all,407.77,408.00,DT,piemanpni,all,all,8,419.77,420.00,all,33321,1
33322,about,about,408.00,408.38,IN,piemanpni,about,about,8,420.00,420.38,about,33322,1
33323,it,it,408.39,408.41,PRP,piemanpni,it,it,8,420.39,420.41,it,33323,0

In [6]:
import os 
import pandas as pd
N_factors = 8
Dir_FA = os.path.join(Dir_github,project,'scripts','FactorAnalysis','output')
df_FA = pd.read_csv(os.path.join(Dir_FA,f'data_FA_n{N_factors}.csv'))
df_FA

,idx,Word,Lemma,Fam_Brys,OLD20F,OLD20,Mink_Perceptual_Lanc,CD_Blog_LemmaSum,Cumfreq_TASA,UniphonP_St,...,Consistency_Token_FB_C,Freqtraj_TASA,F1_n8,F2_n8,F3_n8,F4_n8,F5_n8,F6_n8,F7_n8,F8_n8
0,35,abandon,abandon,0.962963,7.450,2.90,2.744282,3.132260,-0.735424,0.049831,...,0.917246,1.059894,0.160709,0.494050,-0.274023,-0.803012,0.664840,-1.257531,0.975810,-0.240104
1,36,abandoned,abandon,1.000000,6.329,3.55,3.075033,3.132260,1.035183,0.051145,...,0.793056,0.935349,0.401931,0.861063,-0.301316,-0.770305,0.815986,-1.026902,-0.480004,-0.334186
2,39,abandoning,abandon,0.962963,6.956,3.70,2.744282,3.132260,-1.543549,0.051486,...,0.957437,0.251768,0.140281,0.977217,0.500563,-0.489144,1.047399,-1.298787,0.572348,-0.377726
3,41,abandons,abandon,0.962963,7.450,2.90,2.744282,3.132260,-0.735424,0.052438,...,0.917246,1.059894,0.088305,0.586460,-0.233246,-0.777023,0.948373,-1.173861,0.666396,-0.224983
4,101,abdomen,abdomen,1.000000,6.386,3.00,4.602757,1.954243,-0.401581,0.047912,...,0.939005,0.660592,-1.213338,0.776602,0.812296,-0.184771,0.160941,1.080471,0.503377,0.119304
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13845,105919,zone,zone,1.000000,8.469,1.40,3.091321,3.145196,1.171116,0.042188,...,0.025341,0.642419,0.630311,-1.515289,0.906688,-0.115375,-1.192884,-0.656951,1.207406,-0.510982
13846,105920,zoned,zone,1.000000,7.131,1.90,3.242207,3.145196,1.171116,0.044226,...,0.134066,0.642419,0.426644,-0.953676,0.654027,0.334660,-0.938703,-0.647832,-0.982571,-1.007818
13847,105921,zones,zone,1.000000,7.791,1.65,3.091321,3.145196,-0.383166,0.040259,...,0.248645,1.412152,0.551074,-1.029902,1.231030,0.183044,-0.861522,-0.619213,0.867422,-0.937866
13848,105922,zoning,zone,1.000000,7.259,2.00,4.005242,3.145196,-1.013596,0.044552,...,0.959106,0.781722,0.349154,-0.284680,1.725670,-0.042970,0.409334,-0.828881,-0.759834,-0.657826
13849,105945,zoology,zoology,1.000000,6.832,2.80,2.946429,1.380211,-1.852771,0.032578,...,0.975598,-0.057453,-2.143722,0.937833,0.443739,0.083175,-1.471271,-0.355091,-0.105980,-0.829105

In [7]:
N_allwords = len(df_timestamps)
df_merge1 = df_timestamps.merge(df_FA, left_on="Word", right_on="Word", how="left")
df_merge2 = df_timestamps.merge(df_FA, left_on="word_gentle", right_on="Word", how="left")
df_merge12 = df_merge1.combine_first(df_merge2)
df_merge3 = df_timestamps.merge(df_FA, left_on="word_lower", right_on="Word", how="left")
df_merge123 = df_merge12.combine_first(df_merge3) # Use this one
df_merge4 = df_timestamps.merge(df_FA, left_on="lemma", right_on="Word", how="left")
df_merge1234 = df_merge123.combine_first(df_merge4) 

df_final = df_merge123.copy()
df_final

,AoA_Kuper,AoA_LWV,Arousal_NRC,Assoc_Freq_Token,Assoc_Freq_Token123,Assoc_Freq_Type,Assoc_Freq_Type123,Auditory_Lanc,BigramF_Avg_C_Log,BigramF_Avg_U_Log,...,idx_y,lemma,offset,offset_addblankTR,onset,onset_addblankTR,transcript,word,word_gentle,word_lower
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,tonight,0.48,3.48,0.12,3.12,tunnel,tonight,tonight,tonight
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,a,0.80,3.80,0.69,3.69,tunnel,a,a,a
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,story,1.21,4.21,0.80,3.80,tunnel,story,story,story
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,by,1.46,4.46,1.21,4.21,tunnel,by,by,by
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,frederik,NaN,NaN,NaN,NaN,tunnel,frederik,NaN,frederik
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33319,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,tell,407.61,419.61,407.41,419.41,piemanpni,tell,tell,tell
33320,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,me,407.77,419.77,407.61,419.61,piemanpni,me,me,me
33321,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,all,408.00,420.00,407.77,419.77,piemanpni,all,all,all
33322,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,about,408.38,420.38,408.00,420.00,piemanpni,about,about,about
33323,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,it,408.41,420.41,408.39,420.39,piemanpni,it,it,it

In [34]:
List_vars_default = ['word','transcript','PoS','functional']
NFA=8
List_vars = [f'F{x}_n{NFA}' for x in range(1,NFA+1)]
df_final[List_vars_default+List_vars].dropna()

,word,transcript,PoS,functional,F1_n8,F2_n8,F3_n8,F4_n8,F5_n8,F6_n8,F7_n8,F8_n8
6,tunnel,tunnel,NN,0,0.184555,-0.245154,-1.603434,1.372686,1.655855,1.229165,0.880983,-0.202244
9,world,tunnel,NN,0,2.350597,-0.669855,-0.375138,0.513442,-0.981136,1.021976,2.848439,3.992304
12,morning,tunnel,NN,0,1.899139,-0.155593,1.307531,-0.219901,0.862658,0.131637,1.370368,1.569908
18,woke,tunnel,VBD,0,0.925322,-1.868737,0.423821,-0.974311,-1.501928,-0.618411,-1.337464,-0.305946
20,screaming,tunnel,VBG,0,0.753769,0.361159,0.316933,1.051840,0.441197,-0.913197,-1.646019,0.880767
...,...,...,...,...,...,...,...,...,...,...,...,...
33308,was,piemanpni,VBD,0,5.145017,-1.712525,-2.293535,-3.378276,-0.804667,-2.376641,-1.310560,-0.797530
33309,hoping,piemanpni,VBG,0,2.106283,-0.657927,1.639270,-0.169657,0.138442,-1.349960,1.248513,0.466107
33311,say,piemanpni,VBP,0,3.303792,-2.783203,-0.373450,-0.923451,-0.501539,-1.151687,1.884122,0.707589
33314,buy,piemanpni,VB,0,1.868357,-2.049046,-2.596040,-1.209915,-1.778001,0.215628,0.951425,1.063289
33317,beer,piemanpni,NN,0,0.828206,-1.907325,-1.795844,-0.976154,0.566032,1.107175,0.413600,4.050993

In [51]:
df_table = df_final[['word','transcript']].dropna().groupby(['transcript']).count()
df_table['tokens_analyze'] = df_final[['F1_n8','onset','transcript']].dropna().groupby(['transcript']).count()['F1_n8']
df_table['tokens_analyze%'] = df_table['tokens_analyze']/df_table['word']*100
df_table['tokens_analyze%'] = df_table['tokens_analyze%'].round(2)
df_table.reset_index(inplace=True)
print('Milkyway: average')
print(df_table.loc[df_table['transcript'].str.contains('milkyway'),['word','tokens_analyze','tokens_analyze%']].mean())
df_table

Milkyway: average
word               1061.000000
tokens_analyze      365.333333
tokens_analyze%      34.433333
dtype: float64

          transcript  word  tokens_analyze  tokens_analyze%
0           21styear  8267            3101            37.51
1              black  1544             538            34.84
2              bronx  1379             426            30.89
3             forgot  2135             742            34.75
4               lucy  1607             530            32.98
5   milkywayoriginal  1059             364            34.37
6   milkywaysynonyms  1066             358            33.58
7      milkywayvodka  1058             374            35.35
8   notthefallintact  1601             525            32.79
9             pieman   957             316            33.02
10         piemanpni   992             328            33.06
11       prettymouth  1970             638            32.39
12      shapessocial   910             394            43.30
13     slumlordreach  5344            1808            33.83
14            tunnel  3435            1049            30.54

word               1061.000000
tokens_analyze      365.333333
tokens_analyze%      34.433333
dtype: float64

In [33]:
df_table['tokens_analyze'].sum()

11609

In [27]:
df_tokens_summary = pd.DataFrame()
for i,df,label in zip(range(5),[df_timestamps,df_merge1,df_merge12,df_merge123,df_merge1234],
                     ['raw','Word','Word_gentle','word_lower','lemma']):
    df_tokens_summary.loc[i,'label'] = label
    df_tokens_summary.loc[i,'tokens_all'] = df[['Word']+[x for x in df.columns if x.startswith('F') and '_n' in x]].dropna()['Word'].shape[0]
    df_tokens_summary.loc[i,'words_all'] = df[['Word']+[x for x in df.columns if x.startswith('F') and '_n' in x]].dropna()['Word'].unique().shape[0]
    df_tokens_summary.loc[i,'tokens_content'] = df[['Word']+[x for x in df.columns if x.startswith('F') and '_n' in x]].dropna().loc[df['functional']==0,'Word'].shape[0]
    df_tokens_summary.loc[i,'words_content'] = df[['Word']+[x for x in df.columns if x.startswith('F') and '_n' in x]].dropna().loc[df['functional']==0,'Word'].unique().shape[0]
    
#     print(f"all words: {N_all_tokens} tokens, {N_all_words} words")
#     print(f"content words: {N_content_tokens} tokens, {N_content_words} words")
for var in ['tokens_all','words_all','tokens_content','words_content']:
    df_tokens_summary[var+'%']  = df_tokens_summary[var]/df_tokens_summary.loc[0,var]
df_tokens_summary

,label,tokens_all,words_all,tokens_content,words_content,tokens_all%,words_all%,tokens_content%,words_content%
0,raw,33324.0,4695.0,23110.0,4496.0,1.000000,1.000000,1.000000,1.000000
1,Word,11143.0,2474.0,10656.0,2457.0,0.334384,0.526944,0.461099,0.546486
2,Word_gentle,11605.0,2704.0,11096.0,2680.0,0.348248,0.575932,0.480138,0.596085
3,word_lower,11609.0,2706.0,11100.0,2682.0,0.348368,0.576358,0.480312,0.596530
4,lemma,11630.0,2721.0,11121.0,2697.0,0.348998,0.579553,0.481220,0.599867

In [9]:
Dir_working = '/work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis'
Nvar = 113
NFA = 8
flag_model = f'Nvar{Nvar}NFA{NFA}_LPAC_multipleReg'

List_vars_default = ['word','onset','transcript','PoS','functional']

mask_PAC_L = '/work/desai-lab/xuanyang/Project/dataset/Nastase/codes/mask/final/rs_HCP_AuditoryMask_L_sm6_100.nii.gz'
mask_PAC_R = '/work/desai-lab/xuanyang/Project/dataset/Nastase/codes/mask/final/rs_HCP_AuditoryMask_R_sm6_100.nii.gz'

List_vars = [f'F{x}_n{NFA}' for x in range(1,NFA+1)]
    
Dir_model = os.path.join(Dir_working,'models',flag_model,f'FA{NFA}')
Dir_results = os.path.join(Dir_model,'results')
Dir_results_1st = os.path.join(Dir_results,'firstlevel')
Dir_results_2nd = os.path.join(Dir_results,'secondlevel')
if not os.path.exists(Dir_results):
    os.makedirs(Dir_results)
if not os.path.exists(Dir_results_1st):
    os.makedirs(Dir_results_1st)
    
Dir_scriptsToRun = os.path.join(Dir_model,'codes','scriptsToRun')
if not os.path.exists(Dir_scriptsToRun):
    os.makedirs(Dir_scriptsToRun)
Dir_log = os.path.join(Dir_model,'codes','logs')
if not os.path.exists(Dir_log):
    os.makedirs(Dir_log)
for i,subID, task,label in zip(df_master.index,df_master.subID,df_master.task,df_master.label):
    idx = "{:03d}".format(i+1)

    df_event = pd.read_csv(df_master.loc[i,'event'],sep='\t')
    blankSecs = df_event.loc[0,'onset']
    df_timestamps_tmp = df_final.loc[df_final['transcript']==label,List_vars_default+List_vars].reset_index(drop=True)
    df_timestamps_tmp['onset'] = df_timestamps_tmp['onset'] + blankSecs
    df_timestamps_tmp['missing'] = 1
    df_timestamps_tmp.loc[df_timestamps_tmp[List_vars].notna().all(axis=1),'missing'] = 0

    Dir_sub = os.path.join(Dir_results_1st,subID)
    if not os.path.exists(Dir_sub):
        os.makedirs(Dir_sub)
    Dir_sub_task = os.path.join(Dir_sub,task)
    if not os.path.exists(Dir_sub_task):
        os.makedirs(Dir_sub_task)

    ### Timings
    # missing
    df_tmp = df_timestamps_tmp.loc[df_timestamps_tmp.missing==1]
    df_tmp.to_csv(os.path.join(Dir_sub_task,'{}_{}_missing.csv'.format(subID,task)),index=False)
    List_output = df_tmp.onset.astype(str).values
    path_missing = os.path.join(Dir_sub_task,'{}_{}_missing.1D'.format(subID,task))
    with open(path_missing,'w') as f:
        f.writelines('\n'.join(List_output))

    # content words
    df_tmp = df_timestamps_tmp.loc[(df_timestamps_tmp.functional==0)&(df_timestamps_tmp.missing==0)]
    df_tmp.to_csv(os.path.join(Dir_sub_task,'{}_{}_cont.csv'.format(subID,task)),index=False)
    List_tmp = [','.join(x) for x in df_tmp[List_vars].astype(str).values]
    List_output =  [x+'*'+y for x,y in zip(df_tmp.onset.astype(str),List_tmp)] 
    path_cont = os.path.join(Dir_sub_task,'{}_{}_cont.1D'.format(subID,task))
    with open(path_cont,'w') as f:
        f.writelines('\n'.join(List_output))

    # functional words
    df_tmp = df_timestamps_tmp.loc[(df_timestamps_tmp.functional==1)&(df_timestamps_tmp.missing==0)]
    df_tmp.to_csv(os.path.join(Dir_sub_task,'{}_{}_func.csv'.format(subID,task)),index=False)
    List_output =  df_tmp.onset.astype(str).values
    path_func = os.path.join(Dir_sub_task,'{}_{}_func.1D'.format(subID,task))
    with open(path_func,'w') as f:
        f.writelines('\n'.join(List_output))


    ### Confounding variables
    path_confounds = df_master.loc[i,'confounding']
    df_confounds = pd.read_csv(path_confounds,sep='\t')
    df_motions = df_confounds[['trans_x','trans_y','trans_z','rot_x','rot_y','rot_z']].copy()
    path_motion = os.path.join(Dir_sub_task,'motions_6.1D')
    #if not os.path.exists(path_motion):
    df_motions.to_csv(path_motion,index=False,header=False,sep=' ')
    list_outlier = [outlier for outlier in df_confounds.columns if 'motion_outlier' in outlier]
    df_confounds['motion_outlier'] = 1-df_confounds[list_outlier].sum(axis=1)
    path_motion_outlier = os.path.join(Dir_sub_task,'motions_outlier.1D')
    df_confounds['motion_outlier'].to_csv(path_motion_outlier,index=False,header=False,sep=' ')

    
    img_smooth = df_master.loc[i,'smooth_clean_rs']
    scriptFile = os.path.join(Dir_sub_task,'Batch_firstlevel_{}_{}.sh'.format(subID,task))
    with open(scriptFile, "w") as f:
            f.write("#!/bin/tcsh\n")
            f.write("/work/apps/AFNI/linux_openmp_64/afni_proc.py -subj_id {} \\\n".format(subID))
            f.write("-scr_overwrite -blocks mask regress \\\n")
            f.write("-mask_import PAC_L {} \\\n".format(mask_PAC_L))
            f.write("-dsets {} \\\n".format(img_smooth))
            f.write("-regress_stim_times {} {} {} \\\n".format(path_cont,path_func,path_missing))
            f.write("-regress_basis 'TENT(1.5,7.5,5)' \\\n")
#                 f.write("-regress_ROI {} {} \\\n".format('PAC_L','PAC_R'))
            f.write("-regress_ROI {} \\\n".format('PAC_L'))
            f.write("-regress_stim_types AM2 times times \\\n")
            f.write("-regress_stim_labels cont func missing \\\n")
            f.write("-regress_opts_3dD -jobs 6 \\\n")
            for iFA in range(1,NFA+1):
                f.write(f"-gltsym 'SYM: cont[{1+5*iFA}] +cont[{2+5*iFA}] +cont[{3+5*iFA}] +cont[{4+5*iFA}]' -glt_label {iFA} FA{iFA}_bin2345 \\\n")
            f.write("-regress_polort 0 \\\n")
            f.write("-regress_3dD_stop \\\n")
            f.write("-regress_reml_exec \\\n")
            f.write("-regress_make_ideal_sum sum_ideal.1D \\\n")
            f.write("-regress_run_clustsim no \\\n")
            f.write("\n")

    masterScript = os.path.join(Dir_scriptsToRun,'run_Batch_firstlevel_{}.sh'.format(idx))
    with open(masterScript, "w") as f:
        f.write("#!/bin/tcsh\n")
        f.write("cd {} \n".format(Dir_sub_task))
        f.write("tcsh {} \n".format(scriptFile))
        f.write("tcsh proc.{} \n".format(subID))
        f.write("rm {}/{}.results/pb00.* \n".format(Dir_sub_task,subID))
        f.write("rm {}/{}.results/all_runs.* \n".format(Dir_sub_task,subID))
        f.write("rm {}/{}.results/fitts.* \n".format(Dir_sub_task,subID))
        f.write("rm {}/{}.results/errts.* \n".format(Dir_sub_task,subID))
    print(iFA,idx,subID)

Dir_codes = os.path.join(Dir_model,'codes')

if not os.path.exists(Dir_log):
    os.makedirs(Dir_log)

jobname = flag_model
ncores = 6
partition = 'desailab-48core'
path_output = os.path.join(Dir_log,jobname)
script_slurm = os.path.join(Dir_codes,'Batch_slurm_firstlevel.sh')
array = '001-213'
#array = '001-013'
with open(script_slurm, "w") as f:
    f.write("#!/bin/sh\n")
    f.write("### name your job \n")
    f.write("#SBATCH --job-name={} \n".format(jobname))
    f.write("### specify number of cores to use \n")
    f.write("#SBATCH -n {} \n".format(ncores))
    f.write("#SBATCH -N 1 \n".format(ncores))
    f.write("### which partition do you want to use? \n")
    f.write("#SBATCH -p {} \n".format(partition))
    f.write("### %a specifies that the output file for each subject will be named according to their array ID \n")
    f.write("# Where to output log files? \n")
    f.write("#SBATCH --output='{}-%A_%a.log' \n".format(path_output))
    f.write("#SBATCH --error='{}-%A_%a.err' \n".format(path_output))
    f.write("### list the subjects that you want to submit in this array \n")
    f.write("#SBATCH --array={} \n".format(array))
    f.write("module load afni \n")
    f.write("module load python3/anaconda/2021.11 \n")
    f.write('echo "Slurm job ID: " $SLURM_JOB_ID \n')
    f.write('echo "Slurm array task ID: " $SLURM_ARRAY_TASK_ID \n')

    f.write('printf -v subj "%03d" $SLURM_ARRAY_TASK_ID \n')
    f.write('echo "Running firstlevel regression on sub-$subj" \n')
    f.write('cd {} \n'.format(Dir_scriptsToRun))
    f.write('tcsh run_Batch_firstlevel_$subj.sh \n')
    f.write('echo "Finished firstlevel regression sub-$subj" \n')
    f.write('date \n')

8 001 sub-023
8 002 sub-023
8 003 sub-030
8 004 sub-030
8 005 sub-032
8 006 sub-032
8 007 sub-034
8 008 sub-034
8 009 sub-049
8 010 sub-050
8 011 sub-052
8 012 sub-052
8 013 sub-058
8 014 sub-065
8 015 sub-066
8 016 sub-075
8 017 sub-079
8 018 sub-079
8 019 sub-081
8 020 sub-081
8 021 sub-083
8 022 sub-083
8 023 sub-084
8 024 sub-086
8 025 sub-086
8 026 sub-087
8 027 sub-087
8 028 sub-088
8 029 sub-088
8 030 sub-089
8 031 sub-089
8 032 sub-090
8 033 sub-090
8 034 sub-091
8 035 sub-091
8 036 sub-093
8 037 sub-093
8 038 sub-095
8 039 sub-095
8 040 sub-096
8 041 sub-096
8 042 sub-097
8 043 sub-097
8 044 sub-098
8 045 sub-098
8 046 sub-099
8 047 sub-099
8 048 sub-100
8 049 sub-100
8 050 sub-101
8 051 sub-101
8 052 sub-102
8 053 sub-102
8 054 sub-103
8 055 sub-103
8 056 sub-104
8 057 sub-104
8 058 sub-106
8 059 sub-106
8 060 sub-107
8 061 sub-107
8 062 sub-108
8 063 sub-108
8 064 sub-109
8 065 sub-109
8 066 sub-110
8 067 sub-110
8 068 sub-111
8 069 sub-111
8 070 sub-127
8 071 sub-127
8 072 sub-131
8 073 sub-136
8 074 sub-143
8 075 sub-145
8 076 sub-186
8 077 sub-190
8 078 sub-190
8 079 sub-201
8 080 sub-221
8 081 sub-222
8 082 sub-223
8 083 sub-225
8 084 sub-228
8 085 sub-229
8 086 sub-230
8 087 sub-231
8 088 sub-232
8 089 sub-233
8 090 sub-234
8 091 sub-235
8 092 sub-235
8 093 sub-236
8 094 sub-237
8 095 sub-244
8 096 sub-249
8 097 sub-265
8 098 sub-265
8 099 sub-265
8 100 sub-265
8 101 sub-265
8 102 sub-267
8 103 sub-267
8 104 sub-267
8 105 sub-268
8 106 sub-272
8 107 sub-273
8 108 sub-273
8 109 sub-273
8 110 sub-273
8 111 sub-274
8 112 sub-274
8 113 sub-274
8 114 sub-274
8 115 sub-275
8 116 sub-275
8 117 sub-275
8 118 sub-275
8 119 sub-279
8 120 sub-280
8 121 sub-280
8 122 sub-280
8 123 sub-284
8 124 sub-284
8 125 sub-284
8 126 sub-284
8 127 sub-285
8 128 sub-285
8 129 sub-285
8 130 sub-285
8 131 sub-286
8 132 sub-286
8 133 sub-287
8 134 sub-288
8 135 sub-288
8 136 sub-288
8 137 sub-288
8 138 sub-289
8 139 sub-289
8 140 sub-290
8 141 sub-290
8 142 sub-290
8 143 sub-290
8 144 sub-291
8 145 sub-291
8 146 sub-291
8 147 sub-291
8 148 sub-292
8 149 sub-292
8 150 sub-292
8 151 sub-292
8 152 sub-293
8 153 sub-294
8 154 sub-294
8 155 sub-294
8 156 sub-294
8 157 sub-295
8 158 sub-295
8 159 sub-295
8 160 sub-297
8 161 sub-298
8 162 sub-298
8 163 sub-298
8 164 sub-298
8 165 sub-299
8 166 sub-299
8 167 sub-300
8 168 sub-300
8 169 sub-301
8 170 sub-301
8 171 sub-301
8 172 sub-301
8 173 sub-302
8 174 sub-302
8 175 sub-303
8 176 sub-303
8 177 sub-304
8 178 sub-304
8 179 sub-304
8 180 sub-304
8 181 sub-305
8 182 sub-305
8 183 sub-306
8 184 sub-306
8 185 sub-307
8 186 sub-307
8 187 sub-307
8 188 sub-308
8 189 sub-308
8 190 sub-308
8 191 sub-308
8 192 sub-309
8 193 sub-309
8 194 sub-309
8 195 sub-309
8 196 sub-310
8 197 sub-310
8 198 sub-310
8 199 sub-310
8 200 sub-311
8 201 sub-312
8 202 sub-312
8 203 sub-312
8 204 sub-312
8 205 sub-313
8 206 sub-313
8 207 sub-313
8 208 sub-313
8 209 sub-314
8 210 sub-314
8 211 sub-314
8 212 sub-314
8 213 sub-315